data_root: /kaggle/input/datasets/awsaf49/asvpoof-2019-dataset/LA/LA

train_audio_dir: ${paths.data_root}/ASVspoof2019_LA_train/flac
dev_audio_dir: ${paths.data_root}/ASVspoof2019_LA_dev/flac
eval_audio_dir: ${paths.data_root}/ASVspoof2019_LA_eval/flac

protocol_dir: ${paths.data_root}/ASVspoof2019_LA_cm_protocols

train_protocol: ${paths.protocol_dir}/ASVspoof2019.LA.cm.train.trn.txt
dev_protocol: ${paths.protocol_dir}/ASVspoof2019.LA.cm.dev.trl.txt
eval_protocol: ${paths.protocol_dir}/ASVspoof2019.LA.cm.eval.trl.txt
