defaults:
  - writer: wandb
  - datasets: asvspoof
  - dataloader: asvspoof
  - paths: kaggle
  - _self_

model:
  _target_: src.model.LCNN

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003
  weight_decay: 0.0001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.5

loss_function:
  _target_: src.loss.AntiSpoofingCrossEntropyLoss
  label_smoothing: 0.0

metrics:
  train:
    - _target_: src.metrics.Accuracy
      name: accuracy
  inference:
    - _target_: src.metrics.Accuracy
      name: accuracy

transforms:
  batch_transforms:
    train: null
    inference: null

trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: null
  device_tensors:
    - features
    - labels
  resume_from: null
  device: auto
  override: False
  monitor: "min dev_loss"
  save_period: 2
  early_stop: 10
  save_dir: "saved"
  seed: 1
